on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:

  build-project:
    name: Build Project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install    
  
      - name: Generate build
        run: npm run build
        env:
          CI: false
      
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: DiyHueUI
          path: build

  release-project:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-project

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: DiyHueUI
      - name: Test artifact download
        run: ls -R

      - name: Archive artifact
        uses: thedoctor0/zip-release@main
        with:
          filename: DiyHueUI.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: DiyHue UI release ${{ github.ref }}
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: DiyHueUI.zip
          asset_name: DiyHueUI-release.zip
          asset_content_type: application/zip
