on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install    
  
      - name: Generate build
        run: npm run build
        env:
          CI: false
      
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build